# Generated by Django 5.2 on 2025-06-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_userprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(default='2025-06-05'),
        ),
    ]
