# Generated by Django 5.2 on 2025-06-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='expiry_date',
        ),
    ]
