# Generated by Django 5.2 on 2025-06-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_rename_description_notice_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='notice',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
