# Generated by Django 5.2 on 2025-06-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_rename_content_notice_description_notice_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
