# Generated by Django 5.2 on 2025-06-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_remove_project_client_remove_project_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Work from Home', 'Work from Home'), ('Emergency Leave', 'Emergency Leave')], max_length=20, null=True),
        ),
    ]
