# Generated by Django 5.2 on 2025-06-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_alter_birthdaycard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdaycard',
            name='image',
        ),
        migrations.AddField(
            model_name='birthdaycard',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='birthday_cards/'),
        ),
    ]
