# Generated by Django 5.2 on 2025-06-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
